### ISSUE TITLE
CSS src url changes relative paths to root

### ISSUE THREAD

**Issue by mevanloon** [flackr/scroll-timeline#261] opened 2024-04-14 20:12 UTC
I have some font faces and image that are referenced relatively to the stylesheet, but those are all converted to "root" paths. So `assets/fonts/coolfont.woff2` would become `/assets/fonts/coolfont.woff2`, which makes it not load.

**Comment by xenoborg** [comment] 2024-04-19 14:35
My fonts work fine

@font-face {
    font-family: alumni-sans;
    src: url('fonts/Alumni_Sans/AlumniSans-VariableFont_wght.ttf');
}

but using the polyfill breaks any background image url or mask image url only in Firefox though, requiring a full web url to fix eg www.mywebsite.co.uk/folder/folder/i/test.png

.content__image {
width: 300px;
height: 300px;
clip-path: polygon(10% 0, 100% 0, 100% 100%, 0 100%);
background-position: center;
background-image: url('i/test.png');
background-repeat: no-repeat;
background-color: black;
background-size: contain;
}

**Comment by weisJ** [comment] 2024-04-23 07:25
I noticed this too. Background images are broken in Firefox (Linux only).

**Comment by weisJ** [comment] 2024-04-24 09:40
This is due to the polyfill for non-inline styles putting the changed stylesheet into blob storage, which seems to have issues in firefox with relative urls. Seems like a non-css version would be very beneficial here. Or at least don't change stylesheets which don't need polyfilling.

**Comment by mevanloon** [comment] 2024-04-28 13:16
Indeed, it would be cool if there was a workaround where we could select what stylesheets to parse, or which ones to ignore. I experience this in webkit btw.

**Comment by robzor** [comment] 2024-06-13 17:08
I am also encountering this with my fonts, the polyfill works fine on Safari but not Firefox. 

This the path which has to be in this format for our Vite config to work:

```
src: url('/fonts/greed-condensed/greed-condensed-heavy.woff2') format('woff2');
```

Does anyone have a fix or a workaround for this? @flackr 

Thanks,

Robin

**Comment by robzor** [comment] 2024-06-14 10:54
@bramus do you have any thoughts on this? You seem to be active in the issues! :)

**Comment by benefiction** [comment] 2024-06-26 17:39
> I am also encountering this with my fonts, the polyfill works fine on Safari but not Firefox.
> 
> This the path which has to be in this format for our Vite config to work:
> 
> ```
> src: url('/fonts/greed-condensed/greed-condensed-heavy.woff2') format('woff2');
> ```
> 
> Does anyone have a fix or a workaround for this? @flackr
> 
> Thanks,
> 
> Robin

Hi Robin,

If you create the scroll-timeline script from this project on your own, you can substitute this line (https://github.com/flackr/scroll-timeline/blob/master/src/scroll-timeline-css-parser.js#L89) with the following lines:
```
    const { origin } = location;
    return p.sheetSrc.replace(/url\(("|'?)\//gm, `url($1${origin}/`);
``` 
Using `replace()` may not be the most efficient solution, but it is more versatile, especially if you're unsure whether you'll be dealing with "url(''), url("") or url() pattern."
![Bildschirmfoto 2024-06-26 um 19 17 25](https://github.com/flackr/scroll-timeline/assets/2339108/24331522-73de-4fa8-9bda-36f3956b93d8)


If you know what you are dealing with, you could use the more performant split().join() approach.


Cheers!

**Comment by MurhafSousli** [comment] 2024-06-30 03:21
@benefiction I tried your solution, forked the project and change that line and built a script. the script still breaks the font when loaded.

reproduction to the issue here https://github.com/MurhafSousli/ngx-scrollbar/issues/615

**Comment by benefiction** [comment] 2024-07-03 15:47
> @benefiction I tried your solution, forked the project and change that line and built a script. the script still breaks the font when loaded.
> 
> reproduction to the issue here [MurhafSousli/ngx-scrollbar#615](https://github.com/MurhafSousli/ngx-scrollbar/issues/615)

@MurhafSousli I see, may this suits better for you:
```
    const { origin } = location;
    return p.sheetSrc.replace(/url\(("|'?)\.?\//gm, `url($1${origin}/`);
```

**Comment by MurhafSousli** [comment] 2024-07-08 21:26
> > @benefiction I tried your solution, forked the project and change that line and built a script. the script still breaks the font when loaded.
> > reproduction to the issue here [MurhafSousli/ngx-scrollbar#615](https://github.com/MurhafSousli/ngx-scrollbar/issues/615)
> 
> @MurhafSousli I see, may this suits better for you:
> 
> ```
>     const { origin } = location;
>     return p.sheetSrc.replace(/url\(("|'?)\.?\//gm, `url($1${origin}/`);
> ```

@benefiction  Wow, that actually worked!

**Comment by MurhafSousli** [comment] 2024-07-08 22:05
@benefiction Is it possible to exclude the view-timeline and also CSS Animations usage? I only need the JS usage for scroll-timeline.

**Comment by oguzhan18** [comment] 2024-08-08 07:52
Hi everyone,

I understand the frustration with the polyfill breaking font faces and background images in Firefox due to the conversion of relative paths to root paths. This issue seems to stem from how the polyfill handles non-inline styles, placing them into blob storage, which causes problems with relative URLs in Firefox.

Proposed Solution
Here's a workaround that modifies the scroll-timeline-css-parser.js file to ensure relative URLs are correctly parsed:

Locate the line that handles URL replacement in scroll-timeline-css-parser.js (line 89).
Replace it with the following code to ensure URLs are correctly prefixed with the origin:

```javascript
const { origin } = location;
return p.sheetSrc.replace(/url\(("|'?)\.?\//gm, `url($1${origin}/`);
```
This code ensures that any relative URL starting with ./ or / is correctly prefixed with the site's origin.

## Example
```html
src: url('fonts/Alumni_Sans/AlumniSans-VariableFont_wght.ttf');
```

**Comment by manuelmeister** [comment] 2024-08-08 08:39
Has this side effects, or could this be fixed in a PR?

**Comment by bramus** [comment] 2024-10-26 22:12
Closing this issue as the PR got merged.

**Closed by bramus** 2024-10-26 22:12 UTC
