### ISSUE TITLE
Polyfill causes background images in firefox to not load

### ISSUE THREAD

**Issue by meta7gear** [flackr/scroll-timeline#275] opened 2024-07-17 14:04 UTC
Including the polyfill either locally or via cdn link is causing all background images to fail loading in on Firefox 128.0 (MacOS BigSur 11.2.3)

<img width="399" alt="image" src="https://github.com/user-attachments/assets/b95b08e5-cff0-4a75-8dad-7bdda351b92d">

**Comment by jhoopmann** [comment] 2024-08-02 10:46
I can confirm this behaviour about animated elements with background images by background: url(..) - in my case an element with an :before pseudo element with background. I am also experiencing problems with animated elements which are using fonts from custom @font-face url(..) rules. Fonts won't be displayed. 
It get's weirder when i put the @font-face rules directly in a <style> tag instead of my applied CSS bundle file, because that's working again.  I am using rem for font-sizes and percentages for the backgrounds, animations are mostly transformations about x/y positioning and scaling.
If i remove the polyfill, everything is displayed as expected. 
I though, the calculations (font-size, height's etc.) may break in firefox between layout updates and different calls of the mutation observer events, but after multiple tries with load events, requestAnimationFrames and timeouts, i don't got a solution so far.

**Comment by manuelmeister** [comment] 2024-08-12 07:27
This should be fixed with #279

**Comment by bramus** [comment] 2024-10-26 22:13
Closing as the PR got merged.

**Closed by bramus** 2024-10-26 22:13 UTC

**Comment by sbrl** [comment] 2025-09-21 14:43
This doesn't seem to  have made its way into a release yet - could one be made at all please?
