### ISSUE TITLE
Any `@layer` declarations mess up the parser

### ISSUE THREAD

**Issue by argyleink** [flackr/scroll-timeline#101] opened 2022-12-01 15:54 UTC
```css
@layer chocolate, vanilla, strawberry;
```

with that anywhere as an inline style, the parser gets confused.

**Comment by bramus** [comment] 2022-12-01 21:01
Duplicate of https://github.com/flackr/scroll-timeline/issues/80

**Closed** 2022-12-01 21:02 UTC
