### ISSUE TITLE
"Uncaught Error: (<anonymous file>): Advanced beyond the end" since a few days

### ISSUE THREAD

**Issue by AlexanderBoenninger** [flackr/scroll-timeline#155] opened 2023-09-17 11:16 UTC
Hey
I get this error in
[scroll-timeline-css-parser.js:714:11](https://flackr.github.io/scroll-timeline/src/scroll-timeline-css-parser.js)

I am loading the file in the head (tried it also in the footer) 
    <script src="https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js"></script>

It worked a few days ago. 
probably something with the latest changes?

I tested in Firefox

**Comment by bramus** [comment] 2023-09-18 01:01
In the past I’ve seen this error pop up when my CSS was missing a closing `}` somewhere. Maybe that is what is happening? Or are you by any chance using nested CSS? That could also case this.

Checking the commit history, there’s no recent changes that are related to the parser.

**Comment by AlexanderBoenninger** [comment] 2023-09-18 07:04
You are right! I am embarrassed. Sry

Thanks for your quick response.

**Comment by bramus** [comment] 2024-01-29 12:18
Closing this issue as https://github.com/flackr/scroll-timeline/issues/133 is concerned with fixing the root cause.

**Closed by bramus** 2024-01-29 12:18 UTC
