### ISSUE TITLE
Nextjs compatibility 

### ISSUE THREAD

**Issue by AdrienLapasset** [flackr/scroll-timeline#263] opened 2024-04-18 10:16 UTC
Hi!

Does someone know if the polyfill works with next js? I have tried multiple configurations but have not been able to make it.

_Originally posted by @Crispi27 in https://github.com/flackr/scroll-timeline/issues/163#issuecomment-1868564061_

**Comment by bramus** [comment] 2024-04-18 11:40
Duplicate of #240

**Closed by bramus** 2024-04-18 11:40 UTC
